add continous deployment and health check

diff --git a/.github/workflows/CICD.yml b/.github/workflows/CICD.yml
--- a/.github/workflows/CICD.yml
+++ b/.github/workflows/CICD.yml
@@ -58,7 +58,7 @@ jobs:
         run: |
           docker compose exec myapp uv run python -m pytest
 
-  build-and-deploy-on-aws:
+  continous-delivery:
     runs-on: ubuntu-latest
     permissions:
       id-token: write
@@ -79,7 +79,6 @@ jobs:
       - name: login to aws ecr
         uses: aws-actions/amazon-ecr-login@v2
 
-
       - name: Docker Setup Buildx
         uses: docker/setup-buildx-action@v4.1.0
 
@@ -89,3 +88,53 @@ jobs:
           context: .
           push: true
           tags: 285515884731.dkr.ecr.eu-north-1.amazonaws.com/credit-approval:${{ github.sha }}
+
+  continous-deployment:
+    runs-on: self-hosted
+    needs: continous-delivery
+    steps:
+      # - name: checkout
+      #   uses: actions/checkout@v6
+
+      - name: aws login
+        uses: aws-actions/configure-aws-credentials@v6.2.0
+        with:
+          audience: sts.amazonaws.com
+          aws-region: eu-north-1
+          role-to-assume: arn:aws:iam::285515884731:role/credit-approval-ecr
+
+      - name: login to aws ecr
+        uses: aws-actions/amazon-ecr-login@v2
+
+      - name: pull the docker image
+        run: |
+          docker pull 285515884731.dkr.ecr.eu-north-1.amazonaws.com/credit-approval:${{github.sha}}
+
+      - name: run the container and remove old containers
+        run: |
+          docker stop credit-approval || true
+          docker rm credit-approval || true
+          docker run -d -p 8000:8000 \
+          --name credit-approval \
+          -e MONGO_USERNAME=${{secrets.MONGO_USERNAME}} \
+          -e MONGO_PASSWORD=${{secrets.MONGO_PASSWORD}} \
+          -e MLFLOW_TRACKING_USERNAME=${{secrets.MLFLOW_TRACKING_USERNAME}} \
+          -e MLFLOW_TRACKING_PASSWORD=${{secrets.MLFLOW_TRACKING_PASSWORD}} \
+          -e DAGSHUB_USER_TOKEN=${{secrets.DAGSHUB_USER_TOKEN}} \
+          285515884731.dkr.ecr.eu-north-1.amazonaws.com/credit-approval:${{github.sha}}
+
+      - name: health check
+        id: check
+        run: |
+          for i in {1..10}; do
+            curl -f http://localhost:8000/health && exit 0
+            echo "waiting for the app..."
+            sleep 3
+          done
+
+          echo "health check failed"
+          exit 1
+
+      - name: remove all images
+        run: |
+          docker image prune -f
